spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.138.60.227:3306/vip_service_system?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: viptester
    password: Abcd!1234
  redis:
    host: 10.138.60.227
    port: 6399
    password: viphuiyuan
    database: 0
  application:
      name: nacos-cat-server
  cloud:
      nacos:
        discovery:
          server-addr: 127.0.0.1:8848
server:
  port: 9894
debug: true
creditcat:
  url: http://test-vip-service-center.vcredit.com:10000/vip-html/#/
msg:
  sendKey: 1487201BD119A39B
