server:
  port: 8087

spring:
  application:
    name: nacos-order-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  rabbitmq:
    host: 127.0.0.1
    password: guest
    port: 5672
    username: guest
    publisher-confirms: true
    publisher-returns: true
    template:
        mandatory: true
    listener:
        simple:
          acknowledge-mode: manual
          concurrency: 1
          max-concurrency: 1
          retry:
            enabled: true
